/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "gcode.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(gcode_Command, gcode_Command, AUTO)


PB_BIND(gcode_Command_Arg, gcode_Command_Arg, AUTO)


PB_BIND(gcode_Command_Position, gcode_Command_Position, AUTO)




